- name: copy
  hosts: remote
  gather_facts: no  # Disable gathering facts

  tasks:
    - copy:
        src: /home/ansible/temp.conf  
        dest: /home/ansible/temp123.conf
        mode: 0777
        owner: ansible
        group: ansible
        backup: yes
        remote_src: yes
